import { ClientProvider, Header, PromptInput } from '@/components'
import './globals.css'

export const metadata = {
  title: 'AI art Gallery',
  description: 'Generated by devKingsley',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>

          {/* Header */}
          <Header />

          {/* Prompt input */}
          <PromptInput />

          {children}
        </ClientProvider>
      </body>
    </html>
  )
}